project:
  type: website
  output-dir: .
  render:
    - "index.qmd"
    - "course-materials/*.qmd"
    - "lectures/*.qmd"
    - "worksheets/*.qmd"
    - "!early-drafts-archive/**"

quarto-required: ">=1.4.0"

website:
  title: "Evolucion Intro Bio"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Clases"
        href: lectures/index.qmd
      - text: "Materiales"
        href: course-materials/index.qmd
      - text: "Hojas de trabajo"
        href: worksheets/index.qmd